// <auto-generated />
using System;
using Infraestructure.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infraestructure.Data.Migrations
{
    [DbContext(typeof(ConferenceContext))]
    [Migration("20190414171714_AutogenerateGUID")]
    partial class AutogenerateGUID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infraestructure.Data.Models.UserConference", b =>
                {
                    b.Property<Guid>("IdUserConference")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Edad");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Genero");

                    b.Property<string>("Horoscopo");

                    b.Property<string>("Nombre");

                    b.HasKey("IdUserConference");

                    b.ToTable("UserConferences");
                });
#pragma warning restore 612, 618
        }
    }
}
